import type { Deliverable } from '@/lib/types';

export const mockDeliverables: Deliverable[] = [
  {
    id: 'del-1',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    title: 'Q1 Progress Report',
    type: 'Progress Report',
    dueDate: '2025-04-02',
    uploadedAt: '2025-04-02',
    fileName: 'Q1_Report.pdf',
    fileSize: '2.5 MB',
    fileType: 'PDF',
    status: 'reviewed',
    reviewedBy: 'BID Team',
    reviewedAt: '2025-04-05',
    createdAt: '2025-01-15',
    updatedAt: '2025-04-05',
  },
  {
    id: 'del-2',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    title: 'Pitch Deck v2',
    type: 'Pitch Deck',
    dueDate: '2025-03-15',
    uploadedAt: '2025-03-18',
    fileName: 'Pitch_Deck_v2.pptx',
    fileSize: '4.5 MB',
    fileType: 'PPTX',
    status: 'submitted',
    createdAt: '2025-02-01',
    updatedAt: '2025-03-18',
  },
  {
    id: 'del-3',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    title: 'Business Model Canvas',
    type: 'Business Model Canvas',
    dueDate: '2025-04-18',
    status: 'pending',
    createdAt: '2025-01-15',
    updatedAt: '2025-04-01',
  },
  {
    id: 'del-4',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    title: 'Financial Model (3yr)',
    type: 'Financial Model',
    dueDate: '2025-05-01',
    status: 'pending',
    createdAt: '2025-01-15',
    updatedAt: '2025-04-01',
  },
  {
    id: 'del-5',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    title: 'Market Research Document',
    type: 'Market Research',
    dueDate: '2025-03-01',
    uploadedAt: '2025-02-28',
    fileName: 'Market_Research.docx',
    fileSize: '850 KB',
    fileType: 'DOCX',
    status: 'in_review',
    createdAt: '2025-02-01',
    updatedAt: '2025-03-01',
  },
];
