import type { Document } from '@/lib/types';

export const mockDocuments: Document[] = [
  {
    id: 'doc-1',
    title: 'HealthFirst – Investment Memo',
    type: 'memo',
    entrepreneurId: 'ent-3',
    entrepreneurName: 'Nadia Asante',
    generatedAt: '2025-04-09',
    generatedBy: 'Ama D.',
    status: 'final',
    fileUrl: '/documents/healthfirst-memo.pdf',
    sections: ['Executive Summary', 'Company Overview', 'Market Opportunity', 'Financial Highlights', 'BID Programme Journey'],
    createdAt: '2025-04-09',
    updatedAt: '2025-04-09',
  },
  {
    id: 'doc-2',
    title: 'HealthFirst – DD Report',
    type: 'dd_report',
    entrepreneurId: 'ent-3',
    entrepreneurName: 'Nadia Asante',
    generatedAt: '2025-04-08',
    generatedBy: 'Ama D.',
    status: 'final',
    fileUrl: '/documents/healthfirst-dd.pdf',
    createdAt: '2025-04-08',
    updatedAt: '2025-04-08',
  },
  {
    id: 'doc-3',
    title: 'PayBridge Africa – Investment Memo',
    type: 'memo',
    entrepreneurId: 'ent-1',
    entrepreneurName: 'Amara Osei',
    generatedAt: '2025-03-22',
    generatedBy: 'Ama D.',
    status: 'draft',
    fileUrl: '/documents/paybridge-memo-draft.pdf',
    createdAt: '2025-03-22',
    updatedAt: '2025-04-01',
  },
  {
    id: 'doc-4',
    title: 'Cohort 6 – Q1 Progress Report',
    type: 'progress_report',
    cohortId: 'cohort-6',
    generatedAt: '2025-04-01',
    generatedBy: 'Ama D.',
    status: 'sent',
    fileUrl: '/documents/cohort6-q1-report.pdf',
    createdAt: '2025-04-01',
    updatedAt: '2025-04-01',
  },
];
