import type { Entrepreneur, FundingRound } from '@/lib/types';

export const mockEntrepreneurs: Entrepreneur[] = [
  {
    id: 'ent-1',
    userId: 'user-1',
    firstName: 'Amara',
    lastName: 'Osei',
    email: 'amara@paybridge.africa',
    phone: '+233 24 555 0172',
    businessName: 'PayBridge Africa',
    sector: 'Fintech',
    stage: 'Growth',
    cohortId: 'cohort-6',
    cohortName: 'Cohort 6',
    trainerId: 'trainer-1',
    trainerName: 'Kofi Mensah',
    country: 'Ghana',
    city: 'Accra',
    totalFundingRaised: 120000,
    trainingProgress: 68,
    deliverablesCompleted: 4,
    deliverablesTotal: 7,
    lastActive: 'Today',
    status: 'active',
    source: 'admin-invited',
    goalType: 'Fundraising',
    goalAmount: 500000,
    goalDescription: 'Raise Series A to expand into 2 new markets by Q4 2025.',
    jobsCreated: 3,
    jobsWomen: 2,
    jobsMen: 1,
    fundsMobilised: 0,
    lastUpdateSubmitted: 'Q4 2024',
    focusAreas: ['Product', 'Fundraising', 'Fintech'],
    createdAt: '2025-01-15',
    updatedAt: '2025-04-09',
  },
  {
    id: 'ent-2',
    userId: 'user-2',
    firstName: 'Kwame',
    lastName: 'Mensah',
    email: 'kwame@farmlink.gh',
    businessName: 'FarmLink GH',
    sector: 'Agritech',
    stage: 'Idea',
    cohortId: 'cohort-6',
    cohortName: 'Cohort 6',
    trainerId: 'trainer-2',
    trainerName: 'Esi Adu',
    country: 'Ghana',
    totalFundingRaised: 45000,
    trainingProgress: 42,
    deliverablesCompleted: 2,
    deliverablesTotal: 5,
    lastActive: '2d ago',
    status: 'active',
    source: 'admin-invited',
    goalType: 'Milestone-based',
    jobsCreated: 0,
    jobsWomen: 0,
    jobsMen: 0,
    fundsMobilised: 0,
    lastUpdateSubmitted: 'Q3 2024',
    focusAreas: ['Operations', 'Market Research'],
    createdAt: '2025-01-15',
    updatedAt: '2025-04-07',
  },
  {
    id: 'ent-3',
    userId: 'user-3',
    firstName: 'Nadia',
    lastName: 'Asante',
    email: 'nadia@healthfirst.com',
    businessName: 'HealthFirst',
    sector: 'Healthtech',
    stage: 'Scale',
    cohortId: 'prog-2',
    cohortName: 'Investment Readiness',
    trainerId: 'trainer-1',
    trainerName: 'Kofi Mensah',
    country: 'Nigeria',
    city: 'Lagos',
    totalFundingRaised: 280000,
    trainingProgress: 91,
    deliverablesCompleted: 6,
    deliverablesTotal: 7,
    lastActive: '1d ago',
    status: 'active',
    source: 'admin-invited',
    goalType: 'Fundraising',
    goalAmount: 1200000,
    jobsCreated: 8,
    jobsWomen: 5,
    jobsMen: 3,
    fundsMobilised: 150000,
    lastUpdateSubmitted: 'Q1 2025',
    focusAreas: ['Product', 'Fundraising', 'Healthtech'],
    createdAt: '2024-01-15',
    updatedAt: '2025-04-08',
  },
  {
    id: 'ent-4',
    userId: 'user-4',
    firstName: 'Efe',
    lastName: 'Bright',
    email: 'efe@edifylearn.com',
    businessName: 'Edify Learn',
    sector: 'Edtech',
    stage: 'Idea',
    cohortId: 'cohort-6',
    cohortName: 'Cohort 6',
    trainerId: undefined,
    trainerName: undefined,
    country: 'Nigeria',
    city: 'Lagos',
    totalFundingRaised: 20000,
    trainingProgress: 28,
    deliverablesCompleted: 1,
    deliverablesTotal: 5,
    lastActive: '5d ago',
    status: 'unassigned',
    source: 'self-registered',
    goalType: 'Programme completion',
    jobsCreated: 0,
    jobsWomen: 0,
    jobsMen: 0,
    fundsMobilised: 0,
    focusAreas: ['Product', 'Marketing'],
    createdAt: '2025-04-02',
    updatedAt: '2025-04-04',
  },
  {
    id: 'ent-5',
    userId: 'user-5',
    firstName: 'Zara',
    lastName: 'Owusu',
    email: 'zara@logiroute.com',
    businessName: 'LogiRoute',
    sector: 'Logistics',
    stage: 'Growth',
    cohortId: 'cohort-6',
    cohortName: 'Cohort 6',
    trainerId: 'trainer-3',
    trainerName: 'James Tetteh',
    country: 'Ghana',
    city: 'Kumasi',
    totalFundingRaised: 95000,
    trainingProgress: 75,
    deliverablesCompleted: 5,
    deliverablesTotal: 7,
    lastActive: 'Today',
    status: 'active',
    source: 'admin-invited',
    goalType: 'Fundraising',
    goalAmount: 300000,
    jobsCreated: 5,
    jobsWomen: 2,
    jobsMen: 3,
    fundsMobilised: 50000,
    lastUpdateSubmitted: 'Q1 2025',
    focusAreas: ['Operations', 'Technology'],
    createdAt: '2025-01-15',
    updatedAt: '2025-04-09',
  },
  {
    id: 'ent-6',
    userId: 'user-6',
    firstName: 'Tunde',
    lastName: 'Kola',
    email: 'tunde@buildit.ng',
    businessName: 'BuildIt',
    sector: 'Construction',
    stage: 'Idea',
    cohortId: '',
    cohortName: '',
    trainerId: undefined,
    trainerName: undefined,
    country: 'Nigeria',
    city: 'Lagos',
    totalFundingRaised: 0,
    trainingProgress: 0,
    deliverablesCompleted: 0,
    deliverablesTotal: 0,
    lastActive: '3d ago',
    status: 'unassigned',
    source: 'self-registered',
    goalType: 'Programme completion',
    jobsCreated: 0,
    jobsWomen: 0,
    jobsMen: 0,
    fundsMobilised: 0,
    focusAreas: ['Product', 'Strategy'],
    createdAt: '2025-04-05',
    updatedAt: '2025-04-05',
  },
  {
    id: 'ent-7',
    userId: 'user-7',
    firstName: 'Grace',
    lastName: 'Nana',
    email: 'grace@mediscan.ke',
    businessName: 'MediScan',
    sector: 'Healthtech',
    stage: 'Idea',
    cohortId: '',
    cohortName: '',
    trainerId: undefined,
    trainerName: undefined,
    country: 'Kenya',
    city: 'Nairobi',
    totalFundingRaised: 0,
    trainingProgress: 0,
    deliverablesCompleted: 0,
    deliverablesTotal: 0,
    lastActive: '1w ago',
    status: 'unassigned',
    source: 'self-registered',
    goalType: 'Programme completion',
    jobsCreated: 0,
    jobsWomen: 0,
    jobsMen: 0,
    fundsMobilised: 0,
    focusAreas: ['Product', 'Healthtech'],
    createdAt: '2025-04-03',
    updatedAt: '2025-04-03',
  },
  {
    id: 'ent-8',
    userId: 'user-8',
    firstName: 'Kofi',
    lastName: 'Adu',
    email: 'kofi@adulogistics.com',
    businessName: 'Adu Logistics',
    sector: 'Logistics',
    stage: 'Growth',
    cohortId: 'cohort-6',
    cohortName: 'Cohort 6',
    trainerId: 'trainer-2',
    trainerName: 'Esi Adu',
    country: 'Ghana',
    totalFundingRaised: 35000,
    trainingProgress: 55,
    deliverablesCompleted: 3,
    deliverablesTotal: 6,
    lastActive: 'Today',
    status: 'active',
    source: 'admin-invited',
    goalType: 'Milestone-based',
    jobsCreated: 2,
    jobsWomen: 1,
    jobsMen: 1,
    fundsMobilised: 0,
    lastUpdateSubmitted: 'Q4 2024',
    focusAreas: ['Operations', 'Logistics'],
    createdAt: '2025-01-15',
    updatedAt: '2025-04-09',
  },
];

export const mockFundingRounds: FundingRound[] = [
  { id: 'fr-1', entrepreneurId: 'ent-1', round: 'Pre-seed', amount: 30000, date: 'Jan 2023', source: 'pre-BID', status: 'closed' },
  { id: 'fr-2', entrepreneurId: 'ent-1', round: 'Grant – BID', amount: 50000, date: 'Jun 2023', source: 'BID grant', status: 'closed' },
  { id: 'fr-3', entrepreneurId: 'ent-1', round: 'Seed', amount: 40000, date: 'Oct 2024', status: 'closed' },
  { id: 'fr-4', entrepreneurId: 'ent-1', round: 'Series A', amount: 0, date: 'Q3 2025', status: 'planning' },
];

export const stageDefinitions = {
  'Idea': 'Early concept stage — pre-revenue, validating problem/solution fit.',
  'Growth': 'Business has validated revenue and is actively scaling operations.',
  'Scale': 'Established business expanding into new markets, products or team size.',
};

export const sectorList = ['Fintech', 'Agritech', 'Healthtech', 'Edtech', 'Logistics', 'Construction', 'Cleantech', 'Other'];
