import type { Program, Cohort, Module, Content, ContentItem } from '@/lib/types';

export const mockPrograms: Program[] = [
  {
    id: 'prog-1',
    name: 'BID Accelerator – Cohort 6',
    description: 'Core accelerator curriculum covering foundations, business model, fundraising and operations.',
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    maxEntrepreneurs: 20,
    entrepreneurCount: 18,
    trainerCount: 4,
    moduleCount: 5,
    progress: 55,
    status: 'active',
    createdAt: '2024-11-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'prog-2',
    name: 'Investment Readiness for Fintech',
    description: 'Specialised track on investor relations, due diligence prep and term sheets.',
    startDate: '2025-03-01',
    endDate: '2025-09-30',
    maxEntrepreneurs: 15,
    entrepreneurCount: 9,
    trainerCount: 2,
    moduleCount: 3,
    progress: 20,
    status: 'active',
    createdAt: '2025-02-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'prog-3',
    name: 'Women Economic Empowerment',
    description: 'Program supporting women-led businesses across sectors.',
    startDate: '2025-02-01',
    endDate: '2025-08-31',
    maxEntrepreneurs: 12,
    entrepreneurCount: 6,
    trainerCount: 2,
    moduleCount: 4,
    progress: 15,
    status: 'active',
    createdAt: '2025-01-01',
    updatedAt: '2025-03-01',
  },
];

export const mockCohorts: Cohort[] = [
  {
    id: 'cohort-3',
    name: 'Cohort 3',
    programId: 'prog-0',
    year: 2022,
    startDate: '2022-01-01',
    endDate: '2022-12-31',
    entrepreneurCount: 12,
    trainerCount: 3,
    moduleCount: 25,
    progress: 100,
    status: 'completed',
  },
  {
    id: 'cohort-4',
    name: 'Cohort 4',
    programId: 'prog-0',
    year: 2023,
    startDate: '2023-01-01',
    endDate: '2023-12-31',
    entrepreneurCount: 14,
    trainerCount: 3,
    moduleCount: 25,
    progress: 100,
    status: 'completed',
  },
  {
    id: 'cohort-5',
    name: 'Cohort 5',
    programId: 'prog-0',
    year: 2024,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    entrepreneurCount: 15,
    trainerCount: 3,
    moduleCount: 25,
    progress: 90,
    status: 'wrapping_up',
  },
  {
    id: 'cohort-6',
    name: 'Cohort 6',
    programId: 'prog-1',
    year: 2025,
    startDate: '2025-01-01',
    endDate: '2025-12-31',
    entrepreneurCount: 18,
    trainerCount: 4,
    moduleCount: 5,
    progress: 55,
    status: 'active',
  },
];

export const mockModules: Module[] = [
  {
    id: 'mod-1',
    title: 'Introduction to Entrepreneurship in Africa',
    track: 'Foundations',
    duration: '2 weeks',
    trainerId: 'trainer-1',
    trainerName: 'Kofi M.',
    programIds: ['prog-1', 'prog-3'],
    programNames: ['BID Accelerator – Cohort 6', 'Women Economic Empowerment'],
    contentCount: 3,
    completionRate: 100,
    status: 'published',
    createdAt: '2024-12-01',
    updatedAt: '2025-01-15',
  },
  {
    id: 'mod-2',
    title: 'Business Model Canvas Deep Dive',
    track: 'Business Model',
    duration: '3 weeks',
    trainerId: 'trainer-2',
    trainerName: 'Esi A.',
    programIds: ['prog-1'],
    programNames: ['BID Accelerator – Cohort 6'],
    contentCount: 4,
    completionRate: 72,
    status: 'published',
    createdAt: '2024-12-15',
    updatedAt: '2025-02-15',
  },
  {
    id: 'mod-3',
    title: 'Investor Pitch Fundamentals',
    track: 'Fundraising',
    duration: '2 weeks',
    trainerId: 'trainer-1',
    trainerName: 'Kofi M.',
    programIds: ['prog-1', 'prog-2'],
    programNames: ['BID Accelerator – Cohort 6', 'Investment Readiness for Fintech'],
    contentCount: 3,
    completionRate: 58,
    status: 'published',
    createdAt: '2025-01-15',
    updatedAt: '2025-03-01',
  },
  {
    id: 'mod-4',
    title: 'Financial Modelling for Early-Stage Startups',
    track: 'Operations',
    duration: '4 weeks',
    trainerId: 'trainer-3',
    trainerName: 'James T.',
    programIds: ['prog-1'],
    programNames: ['BID Accelerator – Cohort 6'],
    contentCount: 5,
    completionRate: 31,
    status: 'published',
    createdAt: '2025-02-01',
    updatedAt: '2025-03-15',
  },
  {
    id: 'mod-5',
    title: 'Legal Structures for Startups',
    track: 'Legal',
    duration: '1 week',
    trainerId: 'trainer-4',
    trainerName: 'Mabel O.',
    programIds: [],
    programNames: [],
    contentCount: 2,
    completionRate: 0,
    status: 'draft',
    createdAt: '2025-03-01',
    updatedAt: '2025-04-01',
  },
];

export const mockContentItems: ContentItem[] = [
  // Module 1: Introduction
  { id: 'ci-1', title: 'Welcome & overview', type: 'video', moduleId: 'mod-1', moduleName: 'Introduction to Entrepreneurship in Africa', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '18:32', views: 112, status: 'published', sortOrder: 1, createdAt: '2025-01-01', updatedAt: '2025-01-01' },
  { id: 'ci-2', title: 'Reading list', type: 'pdf', moduleId: 'mod-1', moduleName: 'Introduction to Entrepreneurship in Africa', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', views: 85, status: 'published', sortOrder: 2, createdAt: '2025-01-01', updatedAt: '2025-01-01' },
  // Module 2: BMC
  { id: 'ci-3', title: 'Why the canvas matters', type: 'video', moduleId: 'mod-2', moduleName: 'Business Model Canvas Deep Dive', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '9:00', views: 87, status: 'published', sortOrder: 1, createdAt: '2025-01-15', updatedAt: '2025-01-15' },
  { id: 'ci-4', title: 'BMC worksheet', type: 'pdf', moduleId: 'mod-2', moduleName: 'Business Model Canvas Deep Dive', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', views: 72, status: 'published', sortOrder: 2, createdAt: '2025-01-15', updatedAt: '2025-01-15' },
  { id: 'ci-5', title: 'Mapping value proposition', type: 'video', moduleId: 'mod-2', moduleName: 'Business Model Canvas Deep Dive', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '15:00', views: 64, status: 'published', sortOrder: 3, createdAt: '2025-02-01', updatedAt: '2025-02-01' },
  { id: 'ci-6', title: 'Interactive BMC builder', type: 'tool', moduleId: 'mod-2', moduleName: 'Business Model Canvas Deep Dive', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', views: 45, status: 'published', sortOrder: 4, createdAt: '2025-02-01', updatedAt: '2025-02-01' },
  // Module 3: Pitch
  { id: 'ci-7', title: 'Pitch structure', type: 'video', moduleId: 'mod-3', moduleName: 'Investor Pitch Fundamentals', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '16:00', views: 74, status: 'published', sortOrder: 1, createdAt: '2025-02-15', updatedAt: '2025-02-15' },
  { id: 'ci-8', title: 'Handling investor Q&A', type: 'video', moduleId: 'mod-3', moduleName: 'Investor Pitch Fundamentals', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '12:00', views: 68, status: 'published', sortOrder: 2, createdAt: '2025-02-15', updatedAt: '2025-02-15' },
  { id: 'ci-9', title: 'Pitch checklist', type: 'pdf', moduleId: 'mod-3', moduleName: 'Investor Pitch Fundamentals', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', views: 92, status: 'published', sortOrder: 3, createdAt: '2025-02-15', updatedAt: '2025-02-15' },
  // Module 4: Financial Modelling
  { id: 'ci-10', title: 'Financial modelling basics', type: 'video', moduleId: 'mod-4', moduleName: 'Financial Modelling for Early-Stage Startups', programId: 'prog-1', programName: 'BID Accelerator – Cohort 6', duration: '20:00', views: 31, status: 'published', sortOrder: 1, createdAt: '2025-03-01', updatedAt: '2025-03-01' },
];

export const mockContentLibrary: Content[] = [
  {
    id: 'content-1',
    title: 'Introduction to Entrepreneurship in Africa',
    type: 'video',
    track: 'Foundations',
    trainerId: 'trainer-1',
    trainerName: 'Kofi M.',
    programIds: ['prog-1', 'prog-3'],
    programUsages: [
      { programId: 'prog-1', programName: 'Accelerator', moduleName: 'Intro module' },
      { programId: 'prog-3', programName: 'WEE', moduleName: 'Intro module' },
    ],
    duration: '18:32',
    views: 112,
    completionRate: 100,
    status: 'published',
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01',
  },
  {
    id: 'content-2',
    title: 'Why the canvas matters',
    type: 'video',
    track: 'Business Model',
    trainerId: 'trainer-2',
    trainerName: 'Esi A.',
    programIds: ['prog-1'],
    programUsages: [
      { programId: 'prog-1', programName: 'Accelerator', moduleName: 'BMC module' },
    ],
    duration: '9:00',
    views: 87,
    completionRate: 72,
    status: 'published',
    createdAt: '2025-01-15',
    updatedAt: '2025-01-15',
  },
  {
    id: 'content-3',
    title: 'Investor pitch structure',
    type: 'video',
    track: 'Fundraising',
    trainerId: 'trainer-1',
    trainerName: 'Kofi M.',
    programIds: ['prog-1', 'prog-2'],
    programUsages: [
      { programId: 'prog-1', programName: 'Accelerator', moduleName: 'Pitch module' },
      { programId: 'prog-2', programName: 'Readiness', moduleName: 'Pitch module' },
    ],
    duration: '16:00',
    views: 74,
    completionRate: 58,
    status: 'published',
    createdAt: '2025-02-15',
    updatedAt: '2025-02-15',
  },
];
