import type { Trainer } from '@/lib/types';

export const mockTrainers: Trainer[] = [
  {
    id: 'trainer-1',
    userId: 'user-t1',
    firstName: 'Kofi',
    lastName: 'Mensah',
    email: 'kofi.mensah@bid.org',
    role: 'Mentor',
    accessLevel: 'full',
    specialisms: ['Fintech', 'Fundraising', 'Investor Relations'],
    assignedEntrepreneurs: 8,
    sessionsThisMonth: 14,
    avgSatisfaction: 4.8,
    satisfactionCount: 22,
    status: 'active',
    maxEntrepreneurs: 10,
    createdAt: '2024-01-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'trainer-2',
    userId: 'user-t2',
    firstName: 'Esi',
    lastName: 'Adu',
    email: 'esi.adu@bid.org',
    role: 'Trainer',
    accessLevel: 'full',
    specialisms: ['Agritech', 'Operations'],
    assignedEntrepreneurs: 6,
    sessionsThisMonth: 9,
    avgSatisfaction: 4.6,
    satisfactionCount: 14,
    status: 'active',
    maxEntrepreneurs: 8,
    createdAt: '2024-01-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'trainer-3',
    userId: 'user-t3',
    firstName: 'James',
    lastName: 'Tetteh',
    email: 'james.tetteh@bid.org',
    role: 'Trainer',
    accessLevel: 'full',
    specialisms: ['Strategy', 'Logistics'],
    assignedEntrepreneurs: 5,
    sessionsThisMonth: 7,
    avgSatisfaction: 4.5,
    satisfactionCount: 11,
    status: 'active',
    maxEntrepreneurs: 8,
    createdAt: '2024-02-01',
    updatedAt: '2025-04-01',
  },
  {
    id: 'trainer-4',
    userId: 'user-t4',
    firstName: 'Mabel',
    lastName: 'Osei',
    email: 'mabel.osei@bid.org',
    role: 'Guest Expert',
    accessLevel: 'guest',
    accessExpires: '2025-06-30',
    specialisms: ['Legal', 'Compliance'],
    assignedEntrepreneurs: 0,
    sessionsThisMonth: 2,
    avgSatisfaction: 4.9,
    satisfactionCount: 6,
    status: 'expiring',
    maxEntrepreneurs: 3,
    createdAt: '2024-06-01',
    updatedAt: '2025-02-01',
  },
];
